import PushNotification from "react-native-push-notification";

export default class NotifService {

    testPush() {
        PushNotification.localNotification({
            /* iOS and Android properties */
            //id: 0, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
            title: "My Notification Title", // (optional)
            message: "My Notification Message", // (required),
        });
    }
}